import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/global.css";
import DrawerLeft from "@/components/DrawerLeft";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="grid grid-rows-[48px,1fr] min-h-s">
        <div className="flex items-center justify-start bg-teal-100">
          <DrawerLeft />
        </div>
        {children}
      </body>
    </html>
  );
}
